### ISSUE TITLE
Can't setup Shioru bot

### ISSUE THREAD

**Issue by nthduc** [Maseshi/Shioru#10]
![Screenshot 2022-12-11 114536](https://user-images.githubusercontent.com/111686710/206886944-b74d8ef9-46d9-45cd-b24a-4fb5e73207aa.png)
```bash
(node:16592) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Remote monitoring is now available at http://localhost:3000/
[2022-11-11.11:42:6] :: Unhandled Rejection
  Full Error:
    Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
        at WebSocketManager.createShards (F:\Document\Discord\Shioru\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250:15)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Client.login (F:\Document\Discord\Shioru\node_modules\discord.js\src\client\Client.js:232:7) {
      code: 'DisallowedIntents'
    }
    Promise {
      <rejected> Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
          at WebSocketManager.createShards (F:\Document\Discord\Shioru\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250:15)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async Client.login (F:\Document\Discord\Shioru\node_modules\discord.js\src\client\Client.js:232:7) {
        code: 'DisallowedIntents'
      }
    }
  Reason: Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
  Promise: [object Promise]
  Package: v3.1.0
  Discord.js: v14.6.0
  Node.js: v16.13.1
```

**Comment by Maseshi** [comment]
You need to enable these options in the [Discord Developer Portal](https://discord.com/developers/applications) by going to **Your Bot > Bot > Privileged Gateway Intents**.

![image](https://user-images.githubusercontent.com/67690321/206888285-2908afa8-33a8-4abd-82bf-a295d943a041.png)

**Comment by nthduc** [comment]
@Maseshi, I get an error when I type the command `Shelp` . Thanks 
![Screenshot 2022-12-11 154022](https://user-images.githubusercontent.com/111686710/206894380-82059860-d7ca-4876-a7bf-ec7a76a64cb6.png)

**Comment by Maseshi** [comment]
https://github.com/Maseshi/Shioru/issues/9 Thanks, I'm aware of this issue and I'll commit it soon.
