### ISSUE TITLE
Hey i got an error with the distube module

### ISSUE THREAD

**Issue by TunxxVN** [Maseshi/Shioru#77]
/home/container/node_modules/distube/dist/index.js:2712
    throw new DisTubeError("INVALID_KEY", sourceName, invalidKey);
    ^
DisTubeError [INVALID_KEY]: 'youtubeIdentityToken' does not need to be provided in DisTubeOptions
    at checkInvalidKey (/home/container/node_modules/distube/dist/index.js:2712:11)
    at new Options (/home/container/node_modules/distube/dist/index.js:1587:5)
    at new DisTube (/home/container/node_modules/distube/dist/index.js:2790:20)
    at Object.<anonymous> (/home/container/source/main.js:158:16)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  errorCode: 'INVALID_KEY'

![image](https://github.com/Maseshi/Shioru/assets/142597374/ab1b4823-b526-4866-ac9e-942b6647f9ea)

**Comment by Maseshi** [comment]
I solved this problem a few days ago.  But I haven't updated the code yet 😅

This issue is caused by a music player package that recently removed the `youtubeIdentityToken` option and I forgot to remove it in the main build.

The solution to this problem is to remove this line of code without any problems.
https://github.com/Maseshi/Shioru/blob/main/source/main.js#L193-L193

Thank you for reporting such errors.

**Comment by TunxxVN** [comment]
> I solved this problem a few days ago. But I haven't updated the code yet 😅 This issue is caused by a music player package that recently removed the `youtubeIdentityToken` option and I forgot to remove it in the main build.
> 
> The solution to this problem is to remove this line of code without any problems.:
> 
> https://github.com/Maseshi/Shioru/blob/c88471923caac3aaeedc45a849a6d70238ec3f20/source/main.js#L193
> 
> Thank you for reporting the problem.

It worked, thank you 🤎
